# Generated by Django 5.2.7 on 2025-10-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('duracao', models.IntegerField()),
                ('ano_lancamento', models.IntegerField()),
                ('sinopse', models.TextField()),
                ('imagem', models.ImageField(upload_to='filmes/imagens/')),
            ],
        ),
    ]
